name: Concurrency and Outputs test
on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.build.outputs.jobVersion }}

concurrency: called

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      jobVersion: ${{ steps.var.outputs.stepVersion }}
      
    steps:
      - id: var
        run: echo "::set-output name=stepVersion::23"
