name: Concurrency and Outputs test
on:
  workflow_call:
    outputs:
      version:
        value: 23

concurrency: called

jobs:
  build:
    runs-on: ubuntu-latest
    
    #outputs:
     # jobVersion: ${{ steps.vars.outputs.jobVersion }}
      
    steps:
      - name: Set output variable
        id: var
        run: echo Hello, World!
        #run: echo "::set-output name=jobVersion::23"
