name: Test
on:
  workflow_call:
    inputs:
      assets:
        type: boolean
        description: Whether to build assets
        default: true
        required: false

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, world!'
  assets:
    runs-on: ubuntu-latest
    if: inputs.assets
    steps:
      - run: echo "assets"
  test:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - run: echo 'Test'
  test-two:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo 'Test 2'
  test-three:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Test 3'
