name: ENV in Shell

on: workflow_dispatch

env:
  SHELL_VAR: bash

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - shello: bash
          
    steps:
      #- shell: ${{ env.SHELL_VAR }}
      - run: echo ${{ matrix.shello }}
